# Dimensional Analysis


## Performing a Dimensional Analysis

Given independent variables $x,y,z$ and dependent variable $w$:

1. List dimensions of all quantites
2. Write down the hypothesized "generalized product" $w = k x^a y^b z^c$
3. Write \& simplify the dimensional version $[w] = [x]^a [y]^b [z]^c$
4. Invoke dimensional compatability to solve.
5. Rewrite your equation, marvel at your awesomeness!


## Activities

### Vocal Chord Frequency

The frequency $f$ of the sound of an organism's vocal chords depend on their length $\ell$, tension $s$ (a force) and mass density $\mu$ (mass per unit length). Find a formula for the frequency $f = f(\ell, s, \mu).$

### Mixer Power

A mixer with power $P$ turns a mixer with wings of length $D$ through a liquid of viscosity $H$. Find a formula for the angular velocity $A = A(P,D,H)$. Note that since angles are dimensionless, we have $[A] = 1/T$. The dimensions of viscosity are $[H] = M/(LT)$.

### Velocity of an Ocean Wave

The velocity $V$ of a large ocean wave depends upon the period $P$, the acceleration of gravity $g$, and the density $\mu$ of the water. Find a formula for the velocity $V=V(P,g,\mu)$.



